### ISSUE TITLE
Code errors out

### ISSUE THREAD

**Issue by aarsanjani** [aws-samples/classify-news-amazon-sagemaker-hugging-face#1]
Details of error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-15-70c495fa43f7> in <module>
      4 huggingface_model = sagemaker.huggingface.HuggingFaceModel(
      5 env={ 'HF_TASK':'text-classification' },
----> 6 model_data=huggingface_estimator_bert.model_data,
      7 role=role,
      8 transformers_version="4.6.1",

/opt/conda/lib/python3.7/site-packages/sagemaker/estimator.py in model_data(self)
   1043             model_uri = self.sagemaker_session.sagemaker_client.describe_training_job(
   1044                 TrainingJobName=self.latest_training_job.name
-> 1045             )["ModelArtifacts"]["S3ModelArtifacts"]
   1046         else:
   1047             logger.warning(

KeyError: 'ModelArtifacts'

**Comment by rodzanto** [comment]
You would get this error if you try to define the model before the training job is completed, as it would not find the model artifact (it's an output of the training job).

I will add a note in the notebook for leaving this clear.

Thank you
